ruby class project/class_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "welcome/index"
  root "welcome#index"

  resources :books
end

ruby class project/class_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby class project/class_project/app/models/book.rb
class Book < ApplicationRecord
    def super_dewey_number
        page_numbers * dewey_decimal
    end
    #demonstration of how we access functions with the Book class
end

ruby class project/class_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby class project/class_project/app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    def show
        @books = Book.find(params[:id])
    end
    def new
        @book = Book.new
    end
    def create
        #render plain: params[:book].inspect
        #inspect the object we created

        #
        params.require(:book).permit!
        @book = Book.new(params[:book])
        if @book.save
            redirect_to book_path(@book)
        end
    end
    def destroy
        @book = Book.find(params[:id])
        @book.destroy

        redirect_to books_path
    end
    def edit
        @book = Book.find(params[:id])
    end
    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            redirect_to @book
        else
            render 'edit'
        end
    end

    private
    def book_params
        params.require(:book).permit!
    end
end

ruby class project/class_project/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
end

ruby class project/class_project/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby class project/class_project/app/helpers/books_helper.rb
module BooksHelper
end

ruby class project/class_project/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ruby class project/class_project/app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>
    <% if @book.errors.any? %>
        <h2>
            <%= pluralize(@book.errors.count, "error") %> prohibited this from being saved.
        </h2>
        <ul>
            <% book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <p><%= form.label :title %></p>
    <p><%= form.text_field :title %></p>
    <p><%= form.label :page_numbers %></p>
    <p><%= form.text_field :page_numbers %></p>
    <p><%= form.label :dewey_decimal %></p>
    <p><%= form.text_field :dewey_decimal %></p>
    <%= form.submit %>
<% end %>

ruby class project/class_project/app/views/books/edit.html.erb
<h1> Edit Book </h1>
<%= render 'form' %>

ruby class project/class_project/app/views/books/index.html.erb
<h1>Books</h1>

<ul>
    <% @books.each do |book| %>
    <li>
        <strong><%= link_to(book.title, book_path(book)) %></strong>
        <small> <%= link_to("Edit", edit_book_path(book)) %></small>
        <small><%= link_to('DESTROY!', book_path(book), 
            method: :delete,
            data: { confirm: "Are you sure?" }
        ) %></small>
    </li>
    <% end %>
<ul>

ruby class project/class_project/app/views/books/new.html.erb
<h1> New Book </h1>
<%= render 'form' %>

ruby class project/class_project/app/views/books/show.html.erb
<h1><%= @books.title %></h1>
Info:
<ul>
    <li> Pages: <%= @books.page_numbers %>
    <li> Dewey: <%= @books.dewey_decimal %>
<ul>

ruby class project/class_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

ruby class project/class_project/app/views/welcome/index.html.erb
<h1>Hi there!</h1>
<p><strong>Ruby is the best!</strong></p>
<p><%= link_to 'View Books', books_path %></p>
<p><%= link_to 'New Book', new_book_path %></p>